-- AlterTable
ALTER TABLE `Project` ADD COLUMN `websiteCategory` ENUM('AUTOMOTIVE', 'BUSINESS_SUPPORT_AND_SUPPLIES', 'COMPUTERS_AND_ELECTRONICS', 'CONTRUCTION_AND_CONTRACTING', 'EDUCATION', 'ENTERTAINMENT', 'FOOD_AND_DINING', 'HEALTH_AND_MEDICINE', 'HOME_AND_GARDEN', 'LEGAl_AND_FINANCIAL', 'MANUFACTURING_WHOLESALE_AND_DISTRIBUTION', 'MERCHANTS_AND_RETAIL', 'PERSONAL_CARE_AND_SERVICES', 'REAL_ESTATE', 'TRAVEL_AND_TRANSPORTATION') NOT NULL DEFAULT 'AUTOMOTIVE',
    ALTER COLUMN `websiteType` DROP DEFAULT;
