-- AlterTable
ALTER TABLE `Project` ADD COLUMN `websiteType` ENUM('ECOMMERCE_WEBSITE', 'BUSINESS_WEBSITE', 'BLOG_WEBSITE', 'PORTFOLIO_WEBSITE', 'EVENT_WEBSITE', 'PERSONAL_WEBSITE', 'MEMBERSHIP_WEBSITE', 'NONPROFIT_WEBSITE', 'INFORMATIONAL_WEBSITE', 'ONLINE_FORUM') NOT NULL DEFAULT 'ECOMMERCE_WEBSITE';
